### PR TITLE
Added formatted corpus in this repo

### PR DESCRIPTION
**Pull request by dev-sabbir**
Sir,
I have completed it. Please check and let me know if all is ok.
Regards,
Md. Sabbir Alam

### CODE REVIEW

**Comment by nishnik** [comment]
@InsomniacSabbir We needed it in Devanagari.

**Comment by dev-sabbir** [comment]
Ok I will try to give the devanagari format. But for now hope this will work. Thank you @nishnik :)

**Comment by kylepjohnson** [comment]
This'll do for now. It might be good to have both Roman and Devangari, until the CLTK has a very good transliterator.

**Comment by dev-sabbir** [comment]
Ok sir. I will try to scrap the devanagari text from that site. :)

**Comment by kylepjohnson** [comment]
OK! Send me a PR in this repo when you have it.

I think it'll be best to have two top-level dirs: `romanized` and `devangari`.

**Pull request merged**
